spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:backend/.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
